name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      uses: tj-actions/docker-run@v2.1.0
      with:
        image: zlofenix/emubuilder:qt5
        name: builder
        options: -v ${{github.workspace}}:/srv
        args: sh -c 'mkdir /srv/build && cd /srv/build && i686-w64-mingw32.shared-cmake .. && make -j 8'
